#!/bin/bash
# 微信公众号封面图快速生成脚本

echo "🎨 微信公众号封面图生成选项"
echo "================================"
echo ""
echo "选择生成方式:"
echo "1. 使用DALL-E 3生成 (需要OpenAI API Key)"
echo "2. 使用Stable Diffusion生成 (本地运行)"
echo "3. 使用Midjourney生成 (需要Discord账号)"
echo "4. 手动设计 (使用设计工具)"
echo ""
echo "📋 封面图要求:"
echo "   尺寸: 900x383像素"
echo "   主题: AI助手能力进化"
echo "   颜色: 科技蓝、白色、灰色"
echo "   元素: AI机器人 + 四大能力图标"
echo ""
echo "💡 提示:"
echo "   已保存配置到 wechat_cover_config.json"
echo "   包含详细的生成提示词(prompt)"
echo ""
echo "🚀 快速开始:"
echo "   查看配置: cat wechat_cover_config.json | jq '.prompt'"
echo "   复制提示词到您的图像生成工具"
