#!/bin/bash
# OpenClaw 高质量新闻监控任务脚本

set -e

echo "🚀 开始执行 OpenClaw 高质量新闻监控任务..."

# 获取当前日期
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M:%S)

echo "📅 日期: $DATE $TIME"

# 搜索 OpenClaw 相关新闻
echo "🔍 搜索 OpenClaw 高质量新闻（国内外兼顾）..."

# 使用 Tavily API 搜索多个维度
cd /Users/jiyingguo/.openclaw/workspace

# 激活虚拟环境
source venv_tavily/bin/activate

# 执行 Python 搜索脚本
python3 << 'PYTHON_SCRIPT'
import os
import json
import requests
import re
from datetime import datetime, timedelta
from pathlib import Path

# Tavily API 配置
TAVILY_API_KEY = "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"
TAVILY_API_URL = "https://api.tavily.com/search"

# 高质量新闻源白名单（优先使用）
HIGH_QUALITY_DOMAINS = [
    # 国内权威媒体
    "xinhuanet.com", "people.com.cn", "cctv.com", "gov.cn",
    "caixin.com", "36kr.com", "juejin.cn", "csdn.net", "zhihu.com",
    "tencent.com", "aliyun.com", "huawei.com", "baidu.com",
    
    # 国外权威媒体
    "github.com", "gitcode.com", "docs.openclaw.ai", "openclaw.ai",
    "medium.com", "dev.to", "hackernoon.com", "techcrunch.com",
    "wired.com", "theverge.com", "arstechnica.com",
    
    # 技术社区
    "stackoverflow.com", "reddit.com/r/OpenClaw", "discord.gg/clawd",
    "twitter.com/OpenClaw", "linkedin.com"
]

# 低质量/可疑域名黑名单
LOW_QUALITY_DOMAINS = [
    "clickbait", "fake-news", "ai-generated-news",
    "content-farm", "spam-site", "low-quality-blog"
]

# 搜索查询列表（国内外兼顾，高质量关键词）
search_queries = [
    # 国内搜索（中文）
    "OpenClaw AI 代理 最新新闻 2026年",
    "OpenClaw 技能 更新 发布",
    "OpenClaw 教程 使用指南 最佳实践",
    "OpenClaw 开源项目 GitHub",
    "OpenClaw 社区 中文 讨论",
    
    # 国外搜索（英文）
    "OpenClaw AI agent latest news 2026 reliable source",
    "OpenClaw new skills release official",
    "OpenClaw tutorial best practices guide",
    "OpenClaw GitHub repository updates",
    "OpenClaw community news announcements"
]

def extract_domain(url):
    """提取域名"""
    if not url:
        return ""
    # 移除协议和路径
    domain = url.replace("https://", "").replace("http://", "").split("/")[0]
    # 移除 www.
    if domain.startswith("www."):
        domain = domain[4:]
    return domain.lower()

def is_high_quality_domain(url):
    """检查是否为高质量域名"""
    domain = extract_domain(url)
    
    # 检查黑名单
    for bad_domain in LOW_QUALITY_DOMAINS:
        if bad_domain in domain:
            return False
    
    # 检查白名单
    for good_domain in HIGH_QUALITY_DOMAINS:
        if good_domain in domain:
            return True
    
    # 默认中等质量
    return "medium"

def filter_low_quality_content(content):
    """过滤低质量内容"""
    if not content:
        return ""
    
    # 移除常见的AI生成标记
    ai_markers = [
        "As an AI language model",
        "I am an AI assistant",
        "generated by AI",
        "AI-generated content",
        "created by artificial intelligence"
    ]
    
    for marker in ai_markers:
        if marker.lower() in content.lower():
            return ""
    
    # 移除过短的内容（可能不完整）
    if len(content.strip()) < 50:
        return ""
    
    return content

def translate_if_needed(text):
    """简单的关键词翻译（实际使用中可集成翻译API）"""
    # 这里只是示例，实际应该调用翻译API
    translations = {
        "OpenClaw": "OpenClaw",
        "AI agent": "AI代理",
        "skills": "技能",
        "tutorial": "教程",
        "update": "更新",
        "release": "发布",
        "community": "社区",
        "GitHub": "GitHub"
    }
    
    for eng, chi in translations.items():
        text = text.replace(eng, chi)
    
    return text

print("🔍 开始高质量新闻搜索...")

all_results = []
quality_scores = {}

for query in search_queries:
    print(f"  搜索: {query}")
    try:
        response = requests.post(
            TAVILY_API_URL,
            json={
                "api_key": TAVILY_API_KEY,
                "query": query,
                "search_depth": "advanced",
                "include_answer": True,
                "max_results": 5,
                "include_domains": HIGH_QUALITY_DOMAINS[:10]  # 优先高质量域名
            },
            timeout=30
        )
        
        if response.status_code == 200:
            data = response.json()
            if "results" in data:
                for result in data["results"]:
                    # 质量评估
                    url = result.get("url", "")
                    domain_quality = is_high_quality_domain(url)
                    
                    # 过滤低质量内容
                    content = filter_low_quality_content(result.get("content", ""))
                    if not content:
                        continue
                    
                    # 计算质量分
                    quality_score = 0
                    if domain_quality == True:
                        quality_score = 1.0  # 高质量域名
                    elif domain_quality == "medium":
                        quality_score = 0.7  # 中等质量
                    else:
                        quality_score = 0.3  # 低质量
                    
                    # 内容长度加分
                    content_length = len(content)
                    if content_length > 500:
                        quality_score += 0.2
                    elif content_length > 200:
                        quality_score += 0.1
                    
                    # 更新结果
                    result["quality_score"] = quality_score
                    result["domain_quality"] = domain_quality
                    result["filtered_content"] = content
                    
                    all_results.append(result)
                
                print(f"    ✅ 获取 {len(data['results'])} 条结果")
        else:
            print(f"    ❌ 请求失败: {response.status_code}")
    except Exception as e:
        print(f"    ❌ 错误: {e}")

# 去重（按 URL）
seen_urls = set()
unique_results = []
for result in all_results:
    url = result.get("url", "")
    if url not in seen_urls:
        seen_urls.add(url)
        unique_results.append(result)

# 按质量分排序（优先高质量）
unique_results.sort(key=lambda x: x.get("quality_score", 0), reverse=True)

# 取前8条最高质量的新闻
top_results = unique_results[:8]

print(f"\n📊 质量筛选结果:")
print(f"  总结果数: {len(all_results)} 条")
print(f"  去重后: {len(unique_results)} 条")
print(f"  高质量精选: {len(top_results)} 条")

# 分类统计
domestic_count = 0
international_count = 0
for result in top_results:
    title = result.get("title", "").lower()
    content = result.get("filtered_content", "").lower()
    
    # 简单的中英文判断
    chinese_chars = len(re.findall(r'[\u4e00-\u9fff]', title + content))
    english_chars = len(re.findall(r'[a-zA-Z]', title + content))
    
    if chinese_chars > english_chars:
        domestic_count += 1
    else:
        international_count += 1

# 生成中文报告
date_str = datetime.now().strftime("%Y-%m-%d")
report_md = f"""# 🤖 OpenClaw 每日高质量新闻监控报告

**报告日期**: {date_str}  
**报告时间**: {datetime.now().strftime("%H:%M:%S")}  
**精选新闻**: {len(top_results)} 条（国内 {domestic_count} 条，国外 {international_count} 条）

---

## 📊 质量保证说明

✅ **来源筛选**: 优先选择权威媒体和官方渠道  
✅ **内容核查**: 过滤AI生成和低质量内容  
✅ **中英兼顾**: 国内外新闻均衡报道  
✅ **可信验证**: 避免假新闻和不可靠来源

---

## 📰 今日精选高质量新闻

"""

for i, result in enumerate(top_results, 1):
    title = result.get("title", "无标题")
    url = result.get("url", "")
    content = result.get("filtered_content", "")
    quality_score = result.get("quality_score", 0)
    domain = extract_domain(url)
    
    # 翻译标题（如果是英文）
    if len(re.findall(r'[a-zA-Z]', title)) > len(re.findall(r'[\u4e00-\u9fff]', title)):
        title = translate_if_needed(title)
    
    # 截取摘要（前150字）
    if len(content) > 150:
        summary = content[:150] + "..."
    else:
        summary = content
    
    # 质量评级
    if quality_score >= 0.9:
        quality_rating = "⭐⭐⭐⭐⭐ (高质量)"
    elif quality_score >= 0.7:
        quality_rating = "⭐⭐⭐⭐ (良好)"
    elif quality_score >= 0.5:
        quality_rating = "⭐⭐⭐ (中等)"
    else:
        quality_rating = "⭐⭐ (一般)"
    
    # 来源类型
    if any(cn_domain in domain for cn_domain in ["cn", "com.cn", "net.cn", "org.cn", "gov.cn"]):
        source_type = "🇨🇳 国内"
    else:
        source_type = "🌍 国际"
    
    report_md += f"""
### {i}. {title}

{source_type} | 🔗 **来源**: [{domain}]({url})  
📊 **质量评级**: {quality_rating}  
📅 **抓取时间**: {datetime.now().strftime("%H:%M:%S")}

📝 **内容摘要**:
{summary}

---
"""

# 添加详细统计
report_md += f"""
## 📈 详细统计

### 来源分布
- **国内新闻**: {domestic_count} 条
- **国际新闻**: {international_count} 条
- **权威媒体**: {sum(1 for r in top_results if r.get('domain_quality') == True)} 条

### 质量分布
- ⭐⭐⭐⭐⭐ 高质量: {sum(1 for r in top_results if r.get('quality_score', 0) >= 0.9)} 条
- ⭐⭐⭐⭐ 良好: {sum(1 for r in top_results if 0.7 <= r.get('quality_score', 0) < 0.9)} 条
- ⭐⭐⭐ 中等: {sum(1 for r in top_results if 0.5 <= r.get('quality_score', 0) < 0.7)} 条

### 过滤统计
- 初始结果: {len(all_results)} 条
- 去重后: {len(unique_results)} 条
- 质量筛选后: {len(top_results)} 条
- 过滤比例: {((len(all_results) - len(top_results)) / len(all_results) * 100):.1f}%

---

## 🔍 搜索关键词

**国内搜索**:
1. OpenClaw AI 代理 最新新闻 2026年
2. OpenClaw 技能 更新 发布
3. OpenClaw 教程 使用指南 最佳实践

**国际搜索**:
1. OpenClaw AI agent latest news 2026 reliable source
2. OpenClaw new skills release official
3. OpenClaw tutorial best practices guide

---

*本报告由 OpenClaw 自动生成，经过严格质量筛选*  
*监控时间: 每天 06:00 (北京时间)*
"""

# 保存报告
output_dir = Path("/Users/jiyingguo/.openclaw/workspace/news_summaries")
output_dir.mkdir(exist_ok=True)

output_file = output_dir / f"openclaw_news_high_quality_{date_str}.md"
with open(output_file, "w", encoding="utf-8") as f:
    f.write(report_md)

print(f"\n✅ 高质量报告已保存: {output_file}")

# 同时保存 JSON 格式
json_file = output_dir / f"openclaw_news_high_quality_{date_str}.json"
with open(json_file, "w", encoding="utf-8") as f:
    json.dump({
        "date": date_str,
        "total_results": len(all_results),
        "unique_results": len(unique_results),
        "high_quality_results": len(top_results),
        "domestic_count": domestic_count,
        "international_count": international_count,
        "results": top_results
    }, f, ensure_ascii=False, indent=2)

print(f"✅ JSON 数据已保存: {json_file}")

print("\n📊 质量筛选总结:")
print(f"  高质量域名: {sum(1 for r in top_results if r.get('domain_quality') == True)} 条")
print(f"  中等质量: {sum(1 for r in top_results if r.get('domain_quality') == 'medium')} 条")
print(f"  国内新闻: {domestic_count} 条")
print(f"  国际新闻: {international_count} 条")

PYTHON_SCRIPT

echo "✅ 新闻搜索完成"

# 发送邮件
echo "📧 发送邮件..."
python3 << 'EMAIL_SCRIPT'
import smtplib
import os
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path

# 邮件配置
SMTP_SERVER = "smtp.qq.com"
SMTP_PORT = 587
SENDER_EMAIL = "86940135@qq.com"
SENDER_PASSWORD = "swqfjvmoupdebhgh"
RECEIVERS = ["86940135@qq.com", "jiyingguo@huawei.com"]

# 读取报告
date_str = datetime.now().strftime("%Y-%m-%d")
report_file = Path(f"/Users/jiyingguo/.openclaw/workspace/news_summaries/openclaw_news_{date_str}.md")

if report_file.exists():
    with open(report_file, "r", encoding="utf-8") as f:
        report_content = f.read()
else:
    report_content = "报告文件未找到"

# 创建邮件
msg = MIMEMultipart("alternative")
msg["Subject"] = f"🤖 OpenClaw 每日新闻监控 - {date_str}"
msg["From"] = SENDER_EMAIL
msg["To"] = ", ".join(RECEIVERS)

# 邮件正文
html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; margin-top: 30px; }}
        h3 {{ color: #2980b9; }}
        a {{ color: #3498db; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        .meta {{ color: #7f8c8d; font-size: 14px; }}
        .summary {{ background: #f8f9fa; padding: 15px; border-radius: 5px; margin: 10px 0; }}
        hr {{ border: none; border-top: 1px solid #ecf0f1; margin: 20px 0; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 2px solid #ecf0f1; color: #7f8c8d; font-size: 12px; }}
    </style>
</head>
<body>
    <h1>🤖 OpenClaw 每日新闻监控报告</h1>
    <p class="meta">报告日期: {date_str}</p>
    <p class="meta">报告时间: {datetime.now().strftime("%H:%M:%S")}</p>
    
    <hr>
    
    <pre style="white-space: pre-wrap; font-family: inherit;">{report_content}</pre>
    
    <div class="footer">
        <p>本报告由 OpenClaw 自动生成</p>
        <p>监控时间: 每天 06:00 (北京时间)</p>
    </div>
</body>
</html>
"""

msg.attach(MIMEText(html_content, "html", "utf-8"))

# 发送邮件
try:
    server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
    server.starttls()
    server.login(SENDER_EMAIL, SENDER_PASSWORD)
    server.sendmail(SENDER_EMAIL, RECEIVERS, msg.as_string())
    server.quit()
    print("✅ 邮件发送成功")
except Exception as e:
    print(f"❌ 邮件发送失败: {e}")

EMAIL_SCRIPT

echo "✅ 任务执行完成"
echo "📁 报告位置: news_summaries/openclaw_news_${DATE}.md"
