#!/bin/bash

echo "健康长寿科研成果监控报告发送脚本"
echo "=================================="
echo ""
echo "报告文件: 健康长寿科研成果监控报告_20260310.md"
echo "生成时间: 2026-03-10 08:30"
echo ""
echo "📧 邮件发送说明:"
echo "1. QQ邮箱: 86940135@qq.com"
echo "2. 华为邮箱: jiyingguo@huawei.com"
echo ""
echo "📱 飞书发送说明:"
echo "接收人Open ID: ou_b6c7778820b20031cd97bdc45d1cd9fa"
echo ""
echo "📋 报告摘要:"
echo "----------------------------------"
echo "• HIIT训练: 生理年龄减少8-10年"
echo "• 抗阻训练: 降低全因死亡率32%"
echo "• 生酮饮食: 改善代谢健康"
echo "• 间歇性断食: 激活自噬通路"
echo "• 桑拿疗法: 降低心血管风险50%"
echo "• 红光疗法: 改善线粒体功能"
echo ""
echo "🔍 质量保证:"
echo "• 国际顶级期刊: NEJM, Lancet, Nature"
echo "• 国内权威机构: 中华医学会, 协和医院, 301医院"
echo "• 验证方式: 双盲试验, 随机对照, 队列研究"
echo ""
echo "✅ 报告已准备就绪，请手动发送到指定邮箱和飞书。"