// ==========================================================================
// 昇腾生态平台 - 扩展组件库 (Form/Table/DataChart)
// Generated by ui-ux-pro-max | 2026-03-26
// ==========================================================================

import React, { useState, useRef, useEffect } from 'react';
import { cn } from './ascend-components';

// --------------------------------------------------------------------------
// Form Components
// --------------------------------------------------------------------------

// Form Field Wrapper
interface FormFieldProps {
  label?: string;
  error?: string;
  helperText?: string;
  required?: boolean;
  children: React.ReactNode;
  className?: string;
}

export const FormField: React.FC<FormFieldProps> = ({
  label,
  error,
  helperText,
  required,
  children,
  className,
}) => {
  return (
    <div className={cn('space-y-2', className)}>
      {label && (
        <label className="block text-sm font-medium text-[var(--color-text-primary)]">
          {label}
          {required && <span className="text-[var(--color-error)] ml-1">*</span>}
        </label>
      )}
      {children}
      {error && (
        <p className="text-sm text-[var(--color-error)]">{error}</p>
      )}
      {helperText && !error && (
        <p className="text-sm text-[var(--color-text-secondary)]">{helperText}</p>
      )}
    </div>
  );
};

// Text Input with validation states
interface InputProps extends React.InputHTMLAttributes<HTMLInputElement> {
  icon?: React.ReactNode;
  rightElement?: React.ReactNode;
  state?: 'default' | 'error' | 'success';
}

export const Input = React.forwardRef<HTMLInputElement, InputProps>(
  ({ className, icon, rightElement, state = 'default', ...props }, ref) => {
    const borderColor = {
      default: 'var(--color-border)',
      error: 'var(--color-error)',
      success: 'var(--color-success)',
    }[state];

    return (
      <div className="relative">
        {icon && (
          <div className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--color-text-tertiary)]">
            {icon}
          </div>
        )}
        <input
          ref={ref}
          className={cn(
            'w-full h-10 px-3 py-2 rounded-md bg-[var(--color-bg-primary)] border transition-colors duration-150',
            'text-[var(--color-text-primary)] placeholder:text-[var(--color-text-tertiary)]',
            'focus:outline-none focus:ring-2 focus:ring-offset-0',
            icon && 'pl-10',
            rightElement && 'pr-10',
            className
          )}
          style={{ borderColor, '--tw-ring-color': state === 'error' ? 'var(--color-error)' : 'var(--color-cta)' } as React.CSSProperties}
          {...props}
        />
        {rightElement && (
          <div className="absolute right-3 top-1/2 -translate-y-1/2">
            {rightElement}
          </div>
        )}
      </div>
    );
  }
);
Input.displayName = 'Input';

// Textarea
interface TextareaProps extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {
  error?: boolean;
}

export const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
  ({ className, error, ...props }, ref) => {
    return (
      <textarea
        ref={ref}
        className={cn(
          'w-full px-3 py-2 rounded-md bg-[var(--color-bg-primary)] border transition-colors duration-150',
          'text-[var(--color-text-primary)] placeholder:text-[var(--color-text-tertiary)]',
          'focus:outline-none focus:ring-2 focus:ring-[var(--color-cta)] focus:border-transparent',
          'resize-y min-h-[100px]',
          error && 'border-[var(--color-error)]',
          className
        )}
        {...props}
      />
    );
  }
);
Textarea.displayName = 'Textarea';

// Select
interface SelectOption {
  value: string;
  label: string;
  disabled?: boolean;
}

interface SelectProps {
  value?: string;
  onChange?: (value: string) => void;
  options: SelectOption[];
  placeholder?: string;
  disabled?: boolean;
  error?: boolean;
  className?: string;
}

export const Select: React.FC<SelectProps> = ({
  value,
  onChange,
  options,
  placeholder = '请选择',
  disabled,
  error,
  className,
}) => {
  return (
    <select
      value={value}
      onChange={(e) => onChange?.(e.target.value)}
      disabled={disabled}
      className={cn(
        'w-full h-10 px-3 py-2 rounded-md bg-[var(--color-bg-primary)] border transition-colors duration-150',
        'text-[var(--color-text-primary)]',
        'focus:outline-none focus:ring-2 focus:ring-[var(--color-cta)] focus:border-transparent',
        'disabled:opacity-50 disabled:cursor-not-allowed',
        error && 'border-[var(--color-error)]',
        className
      )}
    >
      <option value="" disabled>
        {placeholder}
      </option>
      {options.map((opt) => (
        <option key={opt.value} value={opt.value} disabled={opt.disabled}>
          {opt.label}
        </option>
      ))}
    </select>
  );
};

// Checkbox
interface CheckboxProps {
  checked?: boolean;
  onChange?: (checked: boolean) => void;
  label?: string;
  disabled?: boolean;
  className?: string;
}

export const Checkbox: React.FC<CheckboxProps> = ({
  checked,
  onChange,
  label,
  disabled,
  className,
}) => {
  return (
    <label className={cn('inline-flex items-center gap-2 cursor-pointer', disabled && 'opacity-50 cursor-not-allowed', className)}>
      <div
        className={cn(
          'w-4 h-4 rounded border transition-colors duration-150 flex items-center justify-center',
          checked ? 'bg-[var(--color-cta)] border-[var(--color-cta)]' : 'border-[var(--color-border)] bg-transparent'
        )}
        onClick={() => !disabled && onChange?.(!checked)}
      >
        {checked && (
          <svg className="w-3 h-3 text-[var(--color-text-inverse)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
          </svg>
        )}
      </div>
      <input type="checkbox" checked={checked} onChange={(e) => onChange?.(e.target.checked)} className="sr-only" disabled={disabled} />
      {label && <span className="text-sm text-[var(--color-text-primary)]">{label}</span>}
    </label>
  );
};

// Radio Group
interface RadioOption {
  value: string;
  label: string;
  disabled?: boolean;
}

interface RadioGroupProps {
  value?: string;
  onChange?: (value: string) => void;
  options: RadioOption[];
  disabled?: boolean;
  className?: string;
}

export const RadioGroup: React.FC<RadioGroupProps> = ({
  value,
  onChange,
  options,
  disabled,
  className,
}) => {
  return (
    <div className={cn('space-y-2', className)}>
      {options.map((opt) => (
        <label
          key={opt.value}
          className={cn('inline-flex items-center gap-2 cursor-pointer', disabled && 'opacity-50 cursor-not-allowed')}
        >
          <div
            className={cn(
              'w-4 h-4 rounded-full border transition-colors duration-150 flex items-center justify-center',
              value === opt.value
                ? 'border-[var(--color-cta)] ring-2 ring-[var(--color-cta)] ring-offset-2 ring-offset-[var(--color-bg-primary)]'
                : 'border-[var(--color-border)]'
            )}
            onClick={() => !disabled && onChange?.(opt.value)}
          >
            {value === opt.value && (
              <div className="w-2 h-2 rounded-full bg-[var(--color-cta)]" />
            )}
          </div>
          <input type="radio" checked={value === opt.value} onChange={() => onChange?.(opt.value)} className="sr-only" disabled={disabled} />
          <span className="text-sm text-[var(--color-text-primary)]">{opt.label}</span>
        </label>
      ))}
    </div>
  );
};

// Switch / Toggle
interface SwitchProps {
  checked?: boolean;
  onChange?: (checked: boolean) => void;
  label?: string;
  disabled?: boolean;
  className?: string;
}

export const Switch: React.FC<SwitchProps> = ({
  checked,
  onChange,
  label,
  disabled,
  className,
}) => {
  return (
    <label className={cn('inline-flex items-center gap-3 cursor-pointer', disabled && 'opacity-50 cursor-not-allowed', className)}>
      <div
        className={cn(
          'relative w-11 h-6 rounded-full transition-colors duration-200',
          checked ? 'bg-[var(--color-cta)]' : 'bg-[var(--color-bg-tertiary)]'
        )}
        onClick={() => !disabled && onChange?.(!checked)}
      >
        <div
          className={cn(
            'absolute top-0.5 w-5 h-5 rounded-full bg-white shadow transition-transform duration-200',
            checked ? 'translate-x-5' : 'translate-x-0.5'
          )}
        />
      </div>
      <input type="checkbox" checked={checked} onChange={(e) => onChange?.(e.target.checked)} className="sr-only" disabled={disabled} />
      {label && <span className="text-sm text-[var(--color-text-primary)]">{label}</span>}
    </label>
  );
};

// Form Section
interface FormSectionProps {
  title?: string;
  description?: string;
  children: React.ReactNode;
  className?: string;
}

export const FormSection: React.FC<FormSectionProps> = ({
  title,
  description,
  children,
  className,
}) => {
  return (
    <div className={cn('space-y-4', className)}>
      {title && (
        <div>
          <h3 className="text-lg font-semibold text-[var(--color-text-primary)]">{title}</h3>
          {description && (
            <p className="text-sm text-[var(--color-text-secondary)] mt-1">{description}</p>
          )}
        </div>
      )}
      <div className="space-y-4">{children}</div>
    </div>
  );
};

// Complete Form Example
interface FormData {
  name: string;
  email: string;
  role: string;
  description: string;
  notifications: boolean;
}

interface FormExampleProps {
  onSubmit?: (data: FormData) => void;
}

export const FormExample: React.FC<FormExampleProps> = ({ onSubmit }) => {
  const [formData, setFormData] = useState<FormData>({
    name: '',
    email: '',
    role: '',
    description: '',
    notifications: true,
  });
  const [errors, setErrors] = useState<Partial<Record<keyof FormData, string>>>({});

  const validate = (): boolean => {
    const newErrors: Partial<Record<keyof FormData, string>> = {};
    
    if (!formData.name.trim()) {
      newErrors.name = '请输入名称';
    }
    
    if (!formData.email.trim()) {
      newErrors.email = '请输入邮箱';
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
      newErrors.email = '邮箱格式不正确';
    }
    
    if (!formData.role) {
      newErrors.role = '请选择角色';
    }
    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (validate()) {
      onSubmit?.(formData);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6 max-w-lg">
      <FormSection title="基本信息" description="请填写您的基本信息">
        <FormField label="名称" required error={errors.name}>
          <Input
            value={formData.name}
            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
            placeholder="请输入名称"
            state={errors.name ? 'error' : 'default'}
          />
        </FormField>

        <FormField label="邮箱" required error={errors.email}>
          <Input
            type="email"
            value={formData.email}
            onChange={(e) => setFormData({ ...formData, email: e.target.value })}
            placeholder="请输入邮箱"
            state={errors.email ? 'error' : 'default'}
          />
        </FormField>

        <FormField label="角色" required error={errors.role}>
          <Select
            value={formData.role}
            onChange={(value) => setFormData({ ...formData, role: value })}
            options={[
              { value: 'developer', label: '开发者' },
              { value: 'data-scientist', label: '数据科学家' },
              { value: 'product', label: '产品经理' },
              { value: 'researcher', label: '研究员' },
            ]}
            placeholder="请选择角色"
            error={!!errors.role}
          />
        </FormField>
      </FormSection>

      <FormSection title="其他信息">
        <FormField label="描述" helperText="简单描述您的需求">
          <Textarea
            value={formData.description}
            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
            placeholder="请输入描述..."
          />
        </FormField>

        <Switch
          checked={formData.notifications}
          onChange={(checked) => setFormData({ ...formData, notifications: checked })}
          label="接收邮件通知"
        />
      </FormSection>

      <div className="flex gap-3 pt-4">
        <button
          type="submit"
          className="px-4 py-2 rounded-md bg-[var(--color-cta)] text-[var(--color-text-inverse)] font-medium hover:bg-[var(--color-cta-hover)] transition-colors"
        >
          提交
        </button>
        <button
          type="button"
          onClick={() => setFormData({ name: '', email: '', role: '', description: '', notifications: true })}
          className="px-4 py-2 rounded-md border border-[var(--color-border)] text-[var(--color-text-primary)] hover:bg-[var(--color-bg-secondary)] transition-colors"
        >
          重置
        </button>
      </div>
    </form>
  );
};

// --------------------------------------------------------------------------
// Table Components
// --------------------------------------------------------------------------

// Table Column Definition
interface TableColumn<T> {
  key: keyof T | string;
  title: string;
  width?: string;
  align?: 'left' | 'center' | 'right';
  render?: (row: T, index: number) => React.ReactNode;
}

// Basic Table
interface TableProps<T> {
  columns: TableColumn<T>[];
  data: T[];
  emptyText?: string;
  loading?: boolean;
  onRowClick?: (row: T) => void;
  className?: string;
}

export function Table<T extends Record<string, unknown>>({
  columns,
  data,
  emptyText = '暂无数据',
  loading,
  onRowClick,
  className,
}: TableProps<T>) {
  return (
    <div className={cn('overflow-x-auto rounded-lg border border-[var(--color-border)]', className)}>
      <table className="w-full">
        <thead>
          <tr className="border-b border-[var(--color-border)] bg-[var(--color-bg-secondary)]">
            {columns.map((col) => (
              <th
                key={String(col.key)}
                className={cn(
                  'px-4 py-3 text-xs font-medium text-[var(--color-text-tertiary)] uppercase tracking-wider',
                  col.align === 'center' && 'text-center',
                  col.align === 'right' && 'text-right'
                )}
                style={{ width: col.width }}
              >
                {col.title}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {loading ? (
            <tr>
              <td colSpan={columns.length} className="px-4 py-8 text-center text-[var(--color-text-secondary)]">
                加载中...
              </td>
            </tr>
          ) : data.length === 0 ? (
            <tr>
              <td colSpan={columns.length} className="px-4 py-8 text-center text-[var(--color-text-secondary)]">
                {emptyText}
              </td>
            </tr>
          ) : (
            data.map((row, index) => (
              <tr
                key={index}
                className={cn(
                  'border-b border-[var(--color-border)] last:border-0',
                  'hover:bg-[var(--color-bg-tertiary)]/50 transition-colors',
                  onRowClick && 'cursor-pointer'
                )}
                onClick={() => onRowClick?.(row)}
              >
                {columns.map((col) => (
                  <td
                    key={String(col.key)}
                    className={cn(
                      'px-4 py-3 text-sm text-[var(--color-text-primary)]',
                      col.align === 'center' && 'text-center',
                      col.align === 'right' && 'text-right'
                    )}
                  >
                    {col.render
                      ? col.render(row, index)
                      : String(row[col.key as keyof T] ?? '')}
                  </td>
                ))}
              </tr>
            ))
          )}
        </tbody>
      </table>
    </div>
  );
}

// Data Table with Sorting
interface DataTableProps<T> extends TableProps<T> {
  sortable?: boolean;
  sortKey?: string;
  sortDirection?: 'asc' | 'desc';
  onSort?: (key: string) => void;
}

export function DataTable<T extends Record<string, unknown>>({
  columns,
  data,
  sortable,
  sortKey,
  sortDirection,
  onSort,
  ...props
}: DataTableProps<T>) {
  const handleSort = (key: string) => {
    if (sortable && onSort) {
      onSort(key);
    }
  };

  const SortIcon = ({ columnKey }: { columnKey: string }) => {
    if (!sortable || sortKey !== columnKey) {
      return (
        <svg className="w-4 h-4 text-[var(--color-text-tertiary)] opacity-0 group-hover:opacity-50" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16V4m0 0L3 8m4-4l4 4m6 0v12m0 0l4-4m-4 4l-4-4" />
        </svg>
      );
    }
    return (
      <svg className="w-4 h-4 text-[var(--color-cta)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        {sortDirection === 'asc' ? (
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 15l7-7 7 7" />
        ) : (
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        )}
      </svg>
    );
  };

  return (
    <Table
      columns={columns.map((col) => ({
        ...col,
        title: (
          <div className="flex items-center gap-1 cursor-pointer select-none group" onClick={() => handleSort(String(col.key))}>
            {col.title}
            <SortIcon columnKey={String(col.key)} />
          </div>
        ),
      }))}
      data={data}
      {...props}
    />
  );
}

// --------------------------------------------------------------------------
// Data Visualization Components (Charts)
// --------------------------------------------------------------------------

// Line Chart
interface ChartDataPoint {
  label: string;
  value: number;
}

interface LineChartProps {
  data: ChartDataPoint[];
  height?: number;
  color?: string;
  showArea?: boolean;
  showDots?: boolean;
  className?: string;
}

export const LineChart: React.FC<LineChartProps> = ({
  data,
  height = 200,
  color = 'var(--color-cta)',
  showArea = true,
  showDots = true,
  className,
}) => {
  const maxValue = Math.max(...data.map((d) => d.value));
  const minValue = Math.min(...data.map((d) => d.value));
  const range = maxValue - minValue || 1;

  const points = data.map((d, i) => ({
    x: (i / (data.length - 1)) * 100,
    y: 100 - ((d.value - minValue) / range) * 100,
  }));

  const pathD = points.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p.x} ${p.y}`).join(' ');
  const areaD = `${pathD} L 100 100 L 0 100 Z`;

  return (
    <div className={cn('w-full', className)} style={{ height }}>
      <svg viewBox="0 0 100 100" preserveAspectRatio="none" className="w-full h-full">
        {/* Grid lines */}
        {[0, 25, 50, 75, 100].map((y) => (
          <line key={y} x1="0" y1={y} x2="100" y2={y} stroke="var(--color-border)" strokeWidth="0.2" />
        ))}
        
        {/* Area fill */}
        {showArea && (
          <path d={areaD} fill={color} fillOpacity="0.1" />
        )}
        
        {/* Line */}
        <path d={pathD} fill="none" stroke={color} strokeWidth="0.5" strokeLinecap="round" strokeLinejoin="round" />
        
        {/* Dots */}
        {showDots && points.map((p, i) => (
          <circle
            key={i}
            cx={p.x}
            cy={p.y}
            r="1"
            fill={color}
          />
        ))}
      </svg>
      
      {/* Labels */}
      <div className="flex justify-between mt-2 text-xs text-[var(--color-text-tertiary)]">
        {data.filter((_, i) => i % Math.ceil(data.length / 5) === 0).map((d, i) => (
          <span key={i}>{d.label}</span>
        ))}
      </div>
    </div>
  );
};

// Bar Chart
interface BarChartProps {
  data: ChartDataPoint[];
  height?: number;
  color?: string;
  horizontal?: boolean;
  showValues?: boolean;
  className?: string;
}

export const BarChart: React.FC<BarChartProps> = ({
  data,
  height = 200,
  color = 'var(--color-cta)',
  horizontal,
  showValues,
  className,
}) => {
  const maxValue = Math.max(...data.map((d) => d.value));

  return (
    <div className={cn('w-full', className)} style={{ height }}>
      <div className="flex items-end justify-between gap-2 h-full">
        {data.map((d, i) => {
          const barHeight = (d.value / maxValue) * 100;
          return (
            <div key={i} className="flex-1 flex flex-col items-center gap-1">
              <div className="w-full flex flex-col items-center" style={{ height: '100%' }}>
                {showValues && (
                  <span className="text-xs text-[var(--color-text-secondary)] mb-1">
                    {d.value}
                  </span>
                )}
                <div
                  className="w-full rounded-t transition-all duration-500"
                  style={{
                    height: `${barHeight}%`,
                    backgroundColor: color,
                    opacity: 0.6 + (i / data.length) * 0.4,
                  }}
                />
              </div>
              <span className="text-xs text-[var(--color-text-tertiary)] truncate max-w-full">
                {d.label}
              </span>
            </div>
          );
        })}
      </div>
    </div>
  );
};

// Donut / Pie Chart
interface DonutChartProps {
  data: { label: string; value: number; color: string }[];
  size?: number;
  strokeWidth?: number;
  showLegend?: boolean;
  className?: string;
}

export const DonutChart: React.FC<DonutChartProps> = ({
  data,
  size = 200,
  strokeWidth = 20,
  showLegend = true,
  className,
}) => {
  const total = data.reduce((sum, d) => sum + d.value, 0);
  const radius = (size - strokeWidth) / 2;
  const circumference = 2 * Math.PI * radius;
  let offset = 0;

  return (
    <div className={cn('flex items-center gap-6', className)}>
      <div className="relative" style={{ width: size, height: size }}>
        <svg viewBox={`0 0 ${size} ${size}`} className="transform -rotate-90">
          {/* Background circle */}
          <circle
            cx={size / 2}
            cy={size / 2}
            r={radius}
            fill="none"
            stroke="var(--color-bg-tertiary)"
            strokeWidth={strokeWidth}
          />
          
          {/* Data segments */}
          {data.map((d, i) => {
            const percentage = d.value / total;
            const dashLength = circumference * percentage;
            const dashOffset = circumference - offset;
            offset += dashLength;

            return (
              <circle
                key={i}
                cx={size / 2}
                cy={size / 2}
                r={radius}
                fill="none"
                stroke={d.color}
                strokeWidth={strokeWidth}
                strokeDasharray={`${dashLength} ${circumference - dashLength}`}
                strokeDashoffset={dashOffset}
                className="transition-all duration-500"
              />
            );
          })}
        </svg>
        
        {/* Center text */}
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <span className="text-2xl font-bold text-[var(--color-text-primary)]">{total}</span>
          <span className="text-xs text-[var(--color-text-secondary)]">总计</span>
        </div>
      </div>

      {/* Legend */}
      {showLegend && (
        <div className="space-y-2">
          {data.map((d, i) => (
            <div key={i} className="flex items-center gap-2">
              <div className="w-3 h-3 rounded-sm" style={{ backgroundColor: d.color }} />
              <span className="text-sm text-[var(--color-text-primary)]">{d.label}</span>
              <span className="text-xs text-[var(--color-text-tertiary)]">
                ({Math.round((d.value / total) * 100)}%)
              </span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

// Progress Bar
interface ProgressProps {
  value: number;
  max?: number;
  label?: string;
  showValue?: boolean;
  color?: string;
  size?: 'sm' | 'md' | 'lg';
  className?: string;
}

export const Progress: React.FC<ProgressProps> = ({
  value,
  max = 100,
  label,
  showValue = true,
  color = 'var(--color-cta)',
  size = 'md',
  className,
}) => {
  const percentage = Math.min((value / max) * 100, 100);
  const heights = { sm: '4px', md: '8px', lg: '12px' };

  return (
    <div className={cn('w-full', className)}>
      {(label || showValue) && (
        <div className="flex justify-between mb-1">
          {label && <span className="text-sm text-[var(--color-text-primary)]">{label}</span>}
          {showValue && <span className="text-sm text-[var(--color-text-secondary)]">{Math.round(percentage)}%</span>}
        </div>
      )}
      <div className="w-full rounded-full bg-[var(--color-bg-tertiary)] overflow-hidden" style={{ height: heights[size] }}>
        <div
          className="h-full rounded-full transition-all duration-500"
          style={{ width: `${percentage}%`, backgroundColor: color }}
        />
      </div>
    </div>
  );
};

// Stats Card with Mini Chart
interface StatCardProps {
  title: string;
  value: string | number;
  change?: string;
  trend?: 'up' | 'down' | 'neutral';
  chartData?: number[];
  chartColor?: string;
  className?: string;
}

export const StatCard: React.FC<StatCardProps> = ({
  title,
  value,
  change,
  trend,
  chartData,
  chartColor = 'var(--color-cta)',
  className,
}) => {
  const trendColors = {
    up: 'text-[var(--color-success)]',
    down: 'text-[var(--color-error)]',
    neutral: 'text-[var(--color-text-tertiary)]',
  };

  return (
    <div className={cn('p-4 rounded-lg bg-[var(--color-bg-secondary)] border border-[var(--color-border)]', className)}>
      <div className="flex items-start justify-between mb-2">
        <span className="text-sm text-[var(--color-text-secondary)]">{title}</span>
        {change && (
          <span className={cn('text-xs', trendColors[trend || 'neutral'])}>
            {trend === 'up' ? '↑' : trend === 'down' ? '↓' : ''} {change}
          </span>
        )}
      </div>
      <div className="text-2xl font-bold font-[var(--font-heading)] text-[var(--color-text-primary)] mb-2">
        {value}
      </div>
      {chartData && (
        <div className="h-8">
          <LineChart
            data={chartData.map((v, i) => ({ label: String(i), value: v }))}
            height={32}
            color={chartColor}
            showArea={false}
            showDots={false}
          />
        </div>
      )}
    </div>
  );
};

// ==========================================================================
// Export All
// ==========================================================================

export {
  FormField,
  Input,
  Textarea,
  Select,
  Checkbox,
  RadioGroup,
  Switch,
  FormSection,
  FormExample,
  Table,
  DataTable,
  LineChart,
  BarChart,
  DonutChart,
  Progress,
  StatCard,
};
