{/* ==========================================================================
   昇腾生态平台 - Hero Section
   Generated by ui-ux-pro-max | 2026-03-26
   ========================================================================== */}

import React, { useState, useEffect } from 'react';
import { Button } from './ascend-components';

// --------------------------------------------------------------------------
// Typewriter Effect Hook
// --------------------------------------------------------------------------

function useTypewriter(text: string, speed: number = 50) {
  const [displayText, setDisplayText] = useState('');
  
  useEffect(() => {
    let index = 0;
    const timer = setInterval(() => {
      if (index < text.length) {
        setDisplayText(text.slice(0, index + 1));
        index++;
      } else {
        clearInterval(timer);
      }
    }, speed);
    return () => clearInterval(timer);
  }, [text, speed]);
  
  return displayText;
}

// --------------------------------------------------------------------------
// Floating Particles Background
// --------------------------------------------------------------------------

const FloatingParticles: React.FC = () => {
  return (
    <div className="absolute inset-0 overflow-hidden pointer-events-none">
      {/* Animated gradient orbs */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-[#22C55E]/10 rounded-full blur-3xl animate-pulse" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-[#00BFFF]/10 rounded-full blur-3xl animate-pulse delay-1000" />
      
      {/* Grid pattern */}
      <div 
        className="absolute inset-0 opacity-20"
        style={{
          backgroundImage: `linear-gradient(rgba(34, 197, 94, 0.1) 1px, transparent 1px),
                           linear-gradient(90deg, rgba(34, 197, 94, 0.1) 1px, transparent 1px)`,
          backgroundSize: '50px 50px',
        }}
      />
      
      {/* Floating dots */}
      {[...Array(20)].map((_, i) => (
        <div
          key={i}
          className="absolute w-1 h-1 bg-[#22C55E]/50 rounded-full animate-float"
          style={{
            left: `${Math.random() * 100}%`,
            top: `${Math.random() * 100}%`,
            animationDelay: `${Math.random() * 5}s`,
            animationDuration: `${3 + Math.random() * 4}s`,
          }}
        />
      ))}
    </div>
  );
};

// --------------------------------------------------------------------------
// Terminal Window Component
// --------------------------------------------------------------------------

const TerminalWindow: React.FC<{ children: React.ReactNode; title?: string }> = ({ children, title = 'Terminal' }) => {
  return (
    <div className="rounded-xl overflow-hidden border border-[var(--color-border)] shadow-2xl bg-[#0a0a0f]">
      {/* Terminal Header */}
      <div className="flex items-center gap-2 px-4 py-3 bg-[var(--color-bg-secondary)] border-b border-[var(--color-border)]">
        <div className="flex gap-1.5">
          <div className="w-3 h-3 rounded-full bg-red-500" />
          <div className="w-3 h-3 rounded-full bg-yellow-500" />
          <div className="w-3 h-3 rounded-full bg-green-500" />
        </div>
        <span className="ml-2 text-xs text-[var(--color-text-tertiary)] font-mono">{title}</span>
      </div>
      {/* Terminal Content */}
      <div className="p-4 font-mono text-sm leading-relaxed">
        {children}
      </div>
    </div>
  );
};

// --------------------------------------------------------------------------
// Code Example Component
// --------------------------------------------------------------------------

const CodeBlock: React.FC<{ children: React.ReactNode; output?: string }> = ({ children, output }) => {
  return (
    <TerminalWindow title="Ascend CL">
      <div className="space-y-2">
        <div className="text-[#94A3B8]">
          <span className="text-[#22C55E]">$</span>{' '}
          <span className="text-[#F8FAFC]">ascend run --model resnet50 --input ./data/image.jpg</span>
        </div>
        <div className="text-[#64748B] animate-pulse">Initializing Ascend runtime...</div>
        <div className="text-[#64748B] animate-pulse delay-300">Loading model weights...</div>
        <div className="text-[#00BFFF]">✓ Model loaded successfully</div>
        <div className="text-[#64748B] animate-pulse delay-500">Running inference...</div>
        <div className="text-[#22C55E]">✓ Inference completed in 12.3ms</div>
        {output && (
          <div className="mt-4 pt-4 border-t border-[var(--color-border)]">
            <div className="text-[#94A3B8]">Output:</div>
            <div className="text-[#F8FAFC]">{output}</div>
          </div>
        )}
        {children}
      </div>
    </TerminalWindow>
  );
};

// --------------------------------------------------------------------------
// Stats Counter Component
// --------------------------------------------------------------------------

const StatCounter: React.FC<{ value: string; label: string; description: string }> = ({ value, label, description }) => {
  return (
    <div className="text-center">
      <div className="text-3xl md:text-4xl font-bold font-[var(--font-heading)] text-[var(--color-cta)]">
        {value}
      </div>
      <div className="text-sm font-medium text-[var(--color-text-primary)] mt-1">{label}</div>
      <div className="text-xs text-[var(--color-text-tertiary)] mt-0.5">{description}</div>
    </div>
  );
};

// --------------------------------------------------------------------------
// Feature Card Component
// --------------------------------------------------------------------------

const FeatureCard: React.FC<{
  icon: React.ReactNode;
  title: string;
  description: string;
  highlight?: string;
}> = ({ icon, title, description, highlight }) => {
  return (
    <div className="group p-6 rounded-xl bg-[var(--color-bg-secondary)] border border-[var(--color-border)] hover:border-[var(--color-cta)]/50 transition-all duration-300 hover:shadow-lg hover:shadow-[var(--color-cta)]/5">
      <div className="w-12 h-12 rounded-lg bg-[var(--color-bg-tertiary)] flex items-center justify-center mb-4 group-hover:bg-[var(--color-cta)]/10 transition-colors">
        {icon}
      </div>
      <h3 className="text-lg font-semibold text-[var(--color-text-primary)] mb-2 font-[var(--font-heading)]">
        {title}
      </h3>
      <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed">
        {description}
      </p>
      {highlight && (
        <div className="mt-3 inline-flex items-center gap-1.5 text-xs text-[var(--color-cta)]">
          <span>→</span>
          <span>{highlight}</span>
        </div>
      )}
    </div>
  );
};

// --------------------------------------------------------------------------
// Main Hero Section
// --------------------------------------------------------------------------

export const HeroSection: React.FC = () => {
  const codeOutput = useTypewriter('{"class": "resnet50", "confidence": 0.987}', 30);
  
  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden bg-[var(--color-bg-primary)]">
      <FloatingParticles />
      
      <div className="relative z-10 container mx-auto px-4 py-16 md:py-24">
        {/* Badge */}
        <div className="flex justify-center mb-8">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[var(--color-bg-secondary)] border border-[var(--color-border)]">
            <span className="w-2 h-2 rounded-full bg-[var(--color-cta)] animate-pulse" />
            <span className="text-sm text-[var(--color-text-secondary)]">
              华为昇腾官方支持 · 已适配 300+ 算子
            </span>
          </div>
        </div>
        
        {/* Main Headline */}
        <div className="text-center max-w-4xl mx-auto mb-8">
          <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold font-[var(--font-heading)] leading-tight mb-6">
            <span className="text-[var(--color-text-primary)]">构建下一代</span>
            <br />
            <span className="bg-gradient-to-r from-[#22C55E] via-[#00BFFF] to-[#7B61FF] bg-clip-text text-transparent">
              AI 计算平台
            </span>
          </h1>
          
          <p className="text-lg md:text-xl text-[var(--color-text-secondary)] max-w-2xl mx-auto mb-10 leading-relaxed">
            专为昇腾生态打造的开发者平台，提供高性能推理引擎、丰富的模型库和一站式部署解决方案
          </p>
        </div>
        
        {/* CTA Buttons */}
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-16">
          <Button 
            variant="cta" 
            size="lg"
            leftIcon={
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            }
          >
            立即开始
          </Button>
          <Button 
            variant="outline" 
            size="lg"
            leftIcon={
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            }
          >
            观看演示
          </Button>
        </div>
        
        {/* Code Example */}
        <div className="max-w-3xl mx-auto">
          <CodeBlock output={codeOutput} />
        </div>
        
        {/* Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mt-16 max-w-4xl mx-auto">
          <StatCounter value="300+" label="适配算子" description="覆盖主流AI模型" />
          <StatCounter value="50ms" label="推理延迟" description="端到端优化" />
          <StatCounter value="99.9%" label="服务可用性" description="企业级可靠性" />
          <StatCounter value="10K+" label="开发者" description="活跃社区" />
        </div>
      </div>
      
      {/* Scroll Indicator */}
      <div className="absolute bottom-8 left-1/2 -translate-x-1/2 animate-bounce">
        <svg className="w-6 h-6 text-[var(--color-text-tertiary)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
        </svg>
      </div>
    </section>
  );
};

// --------------------------------------------------------------------------
// Feature Highlights Section
// --------------------------------------------------------------------------

export const FeatureHighlights: React.FC = () => {
  const features = [
    {
      icon: (
        <svg className="w-6 h-6 text-[var(--color-cta)]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17h14a2 2 0 002-2V5a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
        </svg>
      ),
      title: '高性能推理',
      description: '基于昇腾芯片深度优化，推理速度提升3倍，支持批量处理和流式推理',
      highlight: '查看性能基准 →',
    },
    {
      icon: (
        <svg className="w-6 h-6 text-[#00BFFF]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
        </svg>
      ),
      title: '丰富模型库',
      description: '预置100+主流AI模型，覆盖CV/NLP/语音等领域，一键部署',
      highlight: '浏览模型市场 →',
    },
    {
      icon: (
        <svg className="w-6 h-6 text-[#7B61FF]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
        </svg>
      ),
      title: '一站式部署',
      description: '从训练到部署全流程支持，容器化部署，一键上线生产环境',
      highlight: '了解部署方案 →',
    },
    {
      icon: (
        <svg className="w-6 h-6 text-[#F59E0B]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
        </svg>
      ),
      title: '完善文档',
      description: '详尽的中文文档和API参考，配套最佳实践和迁移指南',
      highlight: '阅读文档 →',
    },
  ];
  
  return (
    <section className="relative py-24 bg-[var(--color-bg-primary)]">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-4xl font-bold font-[var(--font-heading)] text-[var(--color-text-primary)] mb-4">
            为什么选择昇腾生态平台？
          </h2>
          <p className="text-lg text-[var(--color-text-secondary)] max-w-2xl mx-auto">
            专为开发者和企业打造的一站式AI基础设施
          </p>
        </div>
        
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {features.map((feature, index) => (
            <FeatureCard key={index} {...feature} />
          ))}
        </div>
      </div>
    </section>
  );
};

// --------------------------------------------------------------------------
// Export All
// --------------------------------------------------------------------------

export { HeroSection, FeatureHighlights };
