{/* ==========================================================================
   昇腾生态平台 - Dashboard Page
   Generated by ui-ux-pro-max | 2026-03-26
   ========================================================================== */}

import React, { useState } from 'react';
import { Card, CardHeader, CardTitle, CardContent, Badge, Avatar, Button, Input } from './ascend-components';

// --------------------------------------------------------------------------
// Types
// --------------------------------------------------------------------------

interface Model {
  id: string;
  name: string;
  type: string;
  status: 'running' | 'stopped' | 'error';
  instances: number;
  created: string;
}

interface MetricsData {
  label: string;
  value: string;
  change: string;
  trend: 'up' | 'down' | 'neutral';
  icon: React.ReactNode;
}

interface LogEntry {
  id: string;
  timestamp: string;
  level: 'info' | 'warning' | 'error';
  message: string;
  service: string;
}

// --------------------------------------------------------------------------
// Icon Components (Lucide-style SVG)
// --------------------------------------------------------------------------

const Icons = {
  Cpu: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z" />
    </svg>
  ),
  Activity: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M22 12h-4l-3 9L9 3l-3 9H2" />
    </svg>
  ),
  HardDrive: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4" />
    </svg>
  ),
  Clock: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  Server: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01" />
    </svg>
  ),
  Zap: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
    </svg>
  ),
  Search: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
    </svg>
  ),
  Plus: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
    </svg>
  ),
  MoreVertical: () => (
    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 5v.01M12 12v.01M12 19v.01M12 6a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2zm0 7a1 1 0 110-2 1 1 0 010 2z" />
    </svg>
  ),
  RefreshCw: () => (
    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
    </svg>
  ),
  Play: () => (
    <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
      <path d="M8 5v14l11-7z" />
    </svg>
  ),
  Square: () => (
    <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
      <rect x="6" y="6" width="12" height="12" rx="2" />
    </svg>
  ),
};

// --------------------------------------------------------------------------
// Metric Card Component
// --------------------------------------------------------------------------

const MetricCard: React.FC<MetricsData> = ({ label, value, change, trend, icon }) => {
  const trendColors = {
    up: 'text-green-400',
    down: 'text-red-400',
    neutral: 'text-[var(--color-text-tertiary)]',
  };
  
  return (
    <Card variant="bordered" padding="md">
      <div className="flex items-start justify-between">
        <div>
          <p className="text-sm text-[var(--color-text-secondary)] mb-1">{label}</p>
          <p className="text-2xl font-bold font-[var(--font-heading)] text-[var(--color-text-primary)]">{value}</p>
          <div className={`flex items-center gap-1 mt-1 text-xs ${trendColors[trend]}`}>
            {trend === 'up' && <span>↑</span>}
            {trend === 'down' && <span>↓</span>}
            <span>{change}</span>
          </div>
        </div>
        <div className="p-2 rounded-lg bg-[var(--color-bg-tertiary)] text-[var(--color-cta)]">
          {icon}
        </div>
      </div>
    </Card>
  );
};

// --------------------------------------------------------------------------
// Model Status Badge
// --------------------------------------------------------------------------

const StatusBadge: React.FC<{ status: Model['status'] }> = ({ status }) => {
  const config = {
    running: { label: '运行中', variant: 'success' as const },
    stopped: { label: '已停止', variant: 'default' as const },
    error: { label: '异常', variant: 'error' as const },
  };
  const { label, variant } = config[status];
  return <Badge variant={variant}>{label}</Badge>;
};

// --------------------------------------------------------------------------
// Model Table Row
// --------------------------------------------------------------------------

const ModelRow: React.FC<{ model: Model }> = ({ model }) => {
  return (
    <tr className="border-b border-[var(--color-border)] hover:bg-[var(--color-bg-tertiary)]/50 transition-colors">
      <td className="py-4 px-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-[var(--color-bg-tertiary)] flex items-center justify-center text-[var(--color-cta)]">
            <Icons.Cpu />
          </div>
          <div>
            <p className="font-medium text-[var(--color-text-primary)]">{model.name}</p>
            <p className="text-xs text-[var(--color-text-tertiary)]">{model.id}</p>
          </div>
        </div>
      </td>
      <td className="py-4 px-4">
        <Badge variant="default">{model.type}</Badge>
      </td>
      <td className="py-4 px-4">
        <StatusBadge status={model.status} />
      </td>
      <td className="py-4 px-4 text-[var(--color-text-secondary)]">
        {model.instances}
      </td>
      <td className="py-4 px-4 text-[var(--color-text-tertiary)] text-sm">
        {model.created}
      </td>
      <td className="py-4 px-4">
        <div className="flex items-center gap-2">
          <button className="p-2 rounded-md hover:bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)] transition-colors">
            <Icons.Play />
          </button>
          <button className="p-2 rounded-md hover:bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)] transition-colors">
            <Icons.Square />
          </button>
          <button className="p-2 rounded-md hover:bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)] transition-colors">
            <Icons.MoreVertical />
          </button>
        </div>
      </td>
    </tr>
  );
};

// --------------------------------------------------------------------------
// Log Entry Row
// --------------------------------------------------------------------------

const LogRow: React.FC<{ entry: LogEntry }> = ({ entry }) => {
  const levelColors = {
    info: 'bg-blue-500/20 text-blue-400',
    warning: 'bg-yellow-500/20 text-yellow-400',
    error: 'bg-red-500/20 text-red-400',
  };
  
  return (
    <div className="flex items-start gap-3 py-3 border-b border-[var(--color-border)] last:border-0">
      <span className="text-xs text-[var(--color-text-tertiary)] font-mono whitespace-nowrap mt-0.5">
        {entry.timestamp}
      </span>
      <span className={`px-2 py-0.5 rounded text-xs font-medium ${levelColors[entry.level]}`}>
        {entry.level.toUpperCase()}
      </span>
      <div className="flex-1 min-w-0">
        <p className="text-sm text-[var(--color-text-primary)]">{entry.message}</p>
        <p className="text-xs text-[var(--color-text-tertiary)]">{entry.service}</p>
      </div>
    </div>
  );
};

// --------------------------------------------------------------------------
// Mini Chart Component (Using CSS-based bars)
// --------------------------------------------------------------------------

const MiniChart: React.FC<{ data: number[]; color?: string }> = ({ data, color = 'var(--color-cta)' }) => {
  const max = Math.max(...data);
  const min = Math.min(...data);
  const range = max - min || 1;
  
  return (
    <div className="flex items-end gap-1 h-12">
      {data.map((value, i) => {
        const height = ((value - min) / range) * 100;
        return (
          <div
            key={i}
            className="w-2 rounded-t transition-all duration-300"
            style={{
              height: `${Math.max(height, 10)}%`,
              backgroundColor: color,
              opacity: 0.6 + (i / data.length) * 0.4,
            }}
          />
        );
      })}
    </div>
  );
};

// --------------------------------------------------------------------------
// Main Dashboard Component
// --------------------------------------------------------------------------

export const DashboardPage: React.FC = () => {
  const [searchQuery, setSearchQuery] = useState('');
  
  // Sample data
  const metrics: MetricsData[] = [
    {
      label: '推理请求',
      value: '12.4K',
      change: '+12.3% vs昨天',
      trend: 'up',
      icon: <Icons.Activity />,
    },
    {
      label: 'GPU利用率',
      value: '78%',
      change: '+5.2%',
      trend: 'up',
      icon: <Icons.Cpu />,
    },
    {
      label: '存储使用',
      value: '2.1 TB',
      change: '64.2%',
      trend: 'neutral',
      icon: <Icons.HardDrive />,
    },
    {
      label: '平均延迟',
      value: '23ms',
      change: '-8.1%',
      trend: 'down',
      icon: <Icons.Zap />,
    },
  ];
  
  const models: Model[] = [
    { id: 'resnet50-v3', name: 'ResNet50', type: 'CV', status: 'running', instances: 3, created: '2026-03-20' },
    { id: 'bert-base', name: 'BERT-base', type: 'NLP', status: 'running', instances: 2, created: '2026-03-18' },
    { id: 'yolov8-l', name: 'YOLOv8-L', type: 'CV', status: 'stopped', instances: 0, created: '2026-03-15' },
    { id: 'whisper-l', name: 'Whisper-Large', type: 'Audio', status: 'error', instances: 1, created: '2026-03-22' },
  ];
  
  const logs: LogEntry[] = [
    { id: '1', timestamp: '19:42:15', level: 'info', message: '模型推理请求处理完成', service: 'inference-engine' },
    { id: '2', timestamp: '19:41:03', level: 'warning', message: 'GPU显存使用率超过80%', service: 'resource-monitor' },
    { id: '3', timestamp: '19:40:22', level: 'info', message: '新模型部署成功', service: 'model-manager' },
    { id: '4', timestamp: '19:38:45', level: 'error', message: 'Whisper-Large实例异常重启', service: 'instance-manager' },
    { id: '5', timestamp: '19:37:12', level: 'info', message: '自动扩缩容触发', service: 'autoscaler' },
  ];
  
  const chartData = [65, 72, 68, 78, 82, 75, 88, 76, 82, 79, 85, 91];
  
  return (
    <div className="min-h-screen bg-[var(--color-bg-primary)]">
      {/* Header */}
      <header className="border-b border-[var(--color-border)] bg-[var(--color-bg-secondary)]">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <h1 className="text-xl font-bold font-[var(--font-heading)] text-[var(--color-text-primary)]">
                昇腾控制台
              </h1>
              <Badge variant="success">生产环境</Badge>
            </div>
            <div className="flex items-center gap-4">
              <Button variant="cta" size="sm" leftIcon={<Icons.Plus />}>
                部署模型
              </Button>
              <Avatar fallback="刘" size="sm" />
            </div>
          </div>
        </div>
      </header>
      
      {/* Main Content */}
      <main className="container mx-auto px-4 py-8">
        {/* Metrics Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          {metrics.map((metric, i) => (
            <MetricCard key={i} {...metric} />
          ))}
        </div>
        
        {/* Main Grid */}
        <div className="grid lg:grid-cols-3 gap-6">
          {/* Models Table - 2/3 width */}
          <div className="lg:col-span-2">
            <Card padding="none">
              <div className="p-4 border-b border-[var(--color-border)]">
                <div className="flex items-center justify-between mb-4">
                  <h2 className="text-lg font-semibold text-[var(--color-text-primary)]">
                    部署的模型
                  </h2>
                  <Button variant="ghost" size="sm" leftIcon={<Icons.RefreshCw />}>
                    刷新
                  </Button>
                </div>
                {/* Search */}
                <div className="relative">
                  <Icons.Search />
                  <input
                    type="text"
                    placeholder="搜索模型..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="w-full h-10 pl-10 pr-4 rounded-lg bg-[var(--color-bg-primary)] border border-[var(--color-border)] text-[var(--color-text-primary)] placeholder:text-[var(--color-text-tertiary)] focus:outline-none focus:ring-2 focus:ring-[var(--color-cta)] focus:border-transparent"
                  />
                  <div className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--color-text-tertiary)]">
                    <Icons.Search />
                  </div>
                </div>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="text-left text-xs text-[var(--color-text-tertiary)] uppercase tracking-wider">
                      <th className="py-3 px-4 font-medium">模型</th>
                      <th className="py-3 px-4 font-medium">类型</th>
                      <th className="py-3 px-4 font-medium">状态</th>
                      <th className="py-3 px-4 font-medium">实例</th>
                      <th className="py-3 px-4 font-medium">创建时间</th>
                      <th className="py-3 px-4 font-medium">操作</th>
                    </tr>
                  </thead>
                  <tbody>
                    {models.map((model) => (
                      <ModelRow key={model.id} model={model} />
                    ))}
                  </tbody>
                </table>
              </div>
            </Card>
          </div>
          
          {/* Right Column - 1/3 width */}
          <div className="space-y-6">
            {/* Performance Chart */}
            <Card padding="md">
              <div className="flex items-center justify-between mb-4">
                <h3 className="text-sm font-medium text-[var(--color-text-primary)]">
                  推理请求趋势
                </h3>
                <span className="text-xs text-[var(--color-text-tertiary)]">过去12小时</span>
              </div>
              <MiniChart data={chartData} />
            </Card>
            
            {/* Recent Logs */}
            <Card padding="none">
              <div className="p-4 border-b border-[var(--color-border)]">
                <div className="flex items-center justify-between">
                  <h3 className="text-sm font-medium text-[var(--color-text-primary)]">
                    最近日志
                  </h3>
                  <Button variant="ghost" size="sm">
                    查看全部
                  </Button>
                </div>
              </div>
              <div className="px-4">
                {logs.map((log) => (
                  <LogRow key={log.id} entry={log} />
                ))}
              </div>
            </Card>
            
            {/* Quick Actions */}
            <Card padding="md">
              <h3 className="text-sm font-medium text-[var(--color-text-primary)] mb-4">
                快速操作
              </h3>
              <div className="space-y-2">
                <Button variant="outline" size="sm" className="w-full justify-start">
                  <Icons.Plus />
                  <span className="ml-2">创建推理服务</span>
                </Button>
                <Button variant="outline" size="sm" className="w-full justify-start">
                  <Icons.Server />
                  <span className="ml-2">管理计算节点</span>
                </Button>
                <Button variant="outline" size="sm" className="w-full justify-start">
                  <Icons.HardDrive />
                  <span className="ml-2">查看存储卷</span>
                </Button>
              </div>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
};

// --------------------------------------------------------------------------
// Export
// --------------------------------------------------------------------------

export { DashboardPage };
