#!/bin/bash
# ==========================================================================
# 昇腾生态平台 - Next.js 项目初始化脚本
# Generated by ui-ux-pro-max | 2026-03-26
# ==========================================================================

set -e

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo_step() {
    echo -e "${BLUE}==>${NC} $1"
}

echo_success() {
    echo -e "${GREEN}✓${NC} $1"
}

echo_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

echo_error() {
    echo -e "${RED}✗${NC} $1"
}

# ==========================================================================
# 配置
# ==========================================================================

PROJECT_NAME="ascend-ecosystem-platform"
TAILWIND_VERSION="3.4.1"
NODE_MIN_VERSION="18.0.0"

# ==========================================================================
# 检查环境
# ==========================================================================

echo_step "检查环境..."

# 检查 Node.js 版本
NODE_VERSION=$(node -v 2>/dev/null | cut -d'v' -f2 | cut -d'.' -f1)
if [ -z "$NODE_VERSION" ]; then
    echo_error "Node.js 未安装"
    exit 1
fi

if [ "$NODE_VERSION" -lt 18 ]; then
    echo_error "Node.js 版本过低 (需要 >= 18.0.0, 当前: $(node -v))"
    exit 1
fi
echo_success "Node.js $(node -v) ✓"

# 检查 npm
if ! command -v npm &> /dev/null; then
    echo_error "npm 未安装"
    exit 1
fi
echo_success "npm $(npm -v) ✓"

# ==========================================================================
# 创建项目
# ==========================================================================

echo_step "创建 Next.js 项目: $PROJECT_NAME"

# 创建项目目录
mkdir -p $PROJECT_NAME
cd $PROJECT_NAME

# 初始化 package.json
cat > package.json << 'EOF'
{
  "name": "ascend-ecosystem-platform",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }
}
EOF

echo_success "package.json 创建完成"

# ==========================================================================
# 安装核心依赖
# ==========================================================================

echo_step "安装核心依赖..."

npm install next@14.1.0 react@18.2.0 react-dom@18.2.0

echo_success "Next.js 14.1.0 安装完成"

# ==========================================================================
# 安装 TypeScript
# ==========================================================================

echo_step "安装 TypeScript..."

npm install -D typescript@5.3.3 @types/react@18.2.48 @types/react-dom@18.2.18 @types/node@20.11.5

echo_success "TypeScript 安装完成"

# ==========================================================================
# 安装 Tailwind CSS
# ==========================================================================

echo_step "安装 Tailwind CSS..."

npm install -D tailwindcss@${TAILWIND_VERSION} postcss@8.4.33 autoprefixer@10.4.17
npm install -D @tailwindcss/forms@0.5.7 @tailwindcss/typography@0.5.10 tailwindcss-animate@1.0.7

echo_success "Tailwind CSS 安装完成"

# ==========================================================================
# 安装 shadcn/ui 依赖
# ==========================================================================

echo_step "安装 shadcn/ui 依赖..."

npm install class-variance-authority@0.7.0 clsx@2.1.0 tailwind-merge@2.2.0 lucide-react@0.309.0

echo_success "shadcn/ui 工具库安装完成"

# ==========================================================================
# 安装 Radix UI 组件
# ==========================================================================

echo_step "安装 Radix UI 组件..."

npm install @radix-ui/react-dialog@1.0.5
npm install @radix-ui/react-dropdown-menu@2.0.6
npm install @radix-ui/react-tabs@1.0.4
npm install @radix-ui/react-tooltip@1.0.7
npm install @radix-ui/react-slot@1.0.2

echo_success "Radix UI 组件安装完成"

# ==========================================================================
# 创建配置文件
# ==========================================================================

echo_step "创建配置文件..."

# Tailwind Config
cat > tailwind.config.ts << 'EOF'
import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        heading: ["JetBrains Mono", "SF Mono", "Fira Code", "monospace"],
        sans: ["IBM Plex Sans", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        mono: ["Fira Code", "JetBrains Mono", "SF Mono", "monospace"],
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        cta: {
          DEFAULT: "var(--cta)",
          foreground: "var(--cta-foreground)",
        },
        success: {
          DEFAULT: "#22C55E",
          light: "#4ADE80",
          dark: "#16A34A",
        },
        warning: {
          DEFAULT: "#F59E0B",
          light: "#FBBF24",
          dark: "#D97706",
        },
        error: {
          DEFAULT: "#EF4444",
          light: "#F87171",
          dark: "#DC2626",
        },
        border: "var(--border)",
        ascend: {
          blue: "#007C92",
          cyan: "#00BFFF",
          dark: "#0A1628",
        },
      },
      borderRadius: {
        lg: "0.75rem",
        md: "0.5rem",
        sm: "0.25rem",
      },
      boxShadow: {
        glow: "0 0 20px rgba(34, 197, 94, 0.5)",
        "glow-cyan": "0 0 20px rgba(0, 191, 255, 0.5)",
      },
      animation: {
        "fade-in": "fadeIn 200ms ease-out",
        "slide-in": "slideIn 200ms ease-out",
        float: "float 3s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideIn: {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
EOF

# PostCSS Config
cat > postcss.config.js << 'EOF'
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
EOF

# TypeScript Config
cat > tsconfig.json << 'EOF'
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF

# Next.js Config
cat > next.config.js << 'EOF'
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: ['images.unsplash.com', 'picsum.photos'],
  },
};

module.exports = nextConfig;
EOF

echo_success "配置文件创建完成"

# ==========================================================================
# 创建目录结构
# ==========================================================================

echo_step "创建目录结构..."

mkdir -p app
mkdir -p components/ui
mkdir -p lib
mkdir -p public

echo_success "目录结构创建完成"

# ==========================================================================
# 创建全局样式
# ==========================================================================

echo_step "创建全局样式..."

cat > app/globals.css << 'EOF'
@import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500;600;700&display=swap');

@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
    --primary: 142 71% 45%;
    --primary-foreground: 222.2 84% 4.9%;
    --secondary: 217.2 32.6% 17.5%;
    --cta: 142 71% 45%;
    --cta-foreground: 0 0 0%;
    --border: 217.2 32.6% 17.5%;
  }

  * {
    @apply border-border;
  }

  body {
    @apply bg-background text-foreground font-sans antialiased;
  }

  /* 代码字体 */
  code, pre {
    @apply font-mono;
  }
}

@layer utilities {
  .text-balance {
    text-wrap: balance;
  }
}
EOF

echo_success "全局样式创建完成"

# ==========================================================================
# 创建工具函数
# ==========================================================================

echo_step "创建工具函数..."

cat > lib/utils.ts << 'EOF'
import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
EOF

echo_success "工具函数创建完成"

# ==========================================================================
# 创建基础 UI 组件
# ==========================================================================

echo_step "创建基础 UI 组件..."

# Button Component
cat > components/ui/button.tsx << 'EOF'
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const buttonVariants = cva(
  "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        cta: "bg-cta text-cta-foreground hover:bg-cta/90 shadow-glow",
        outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
        secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2",
        sm: "h-8 rounded-md px-3 text-xs",
        lg: "h-11 rounded-md px-8",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    );
  }
);
Button.displayName = "Button";

export { Button, buttonVariants };
EOF

# Card Component
cat > components/ui/card.tsx << 'EOF'
import * as React from "react";
import { cn } from "@/lib/utils";

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        "rounded-lg border bg-card text-card-foreground shadow-sm",
        className
      )}
      {...props}
    />
  )
);
Card.displayName = "Card";

const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("flex flex-col space-y-1.5 p-6", className)} {...props} />
  )
);
CardHeader.displayName = "CardHeader";

const CardTitle = React.forwardRef<HTMLParagraphElement, React.HTMLAttributes<HTMLHeadingElement>>(
  ({ className, ...props }, ref) => (
    <h3
      ref={ref}
      className={cn("font-semibold leading-none tracking-tight", className)}
      {...props}
    />
  )
);
CardTitle.displayName = "CardTitle";

const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
  )
);
CardContent.displayName = "CardContent";

export { Card, CardHeader, CardTitle, CardContent };
EOF

echo_success "基础 UI 组件创建完成"

# ==========================================================================
# 创建示例页面
# ==========================================================================

echo_step "创建示例页面..."

cat > app/page.tsx << 'EOF'
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";

export default function Home() {
  return (
    <main className="min-h-screen bg-background">
      {/* Hero Section */}
      <section className="relative overflow-hidden">
        {/* Background Effects */}
        <div className="absolute inset-0 bg-gradient-to-br from-background via-background to-primary/10" />
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/10 rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-cyan-500/10 rounded-full blur-3xl" />

        <div className="relative container mx-auto px-4 py-24">
          {/* Badge */}
          <div className="flex justify-center mb-8">
            <span className="px-4 py-2 rounded-full bg-secondary text-sm text-secondary-foreground">
              华为昇腾官方支持 · 已适配 300+ 算子
            </span>
          </div>

          {/* Headline */}
          <h1 className="text-4xl md:text-6xl font-bold text-center font-heading mb-6">
            <span className="text-foreground">构建下一代</span>
            <br />
            <span className="bg-gradient-to-r from-primary via-cyan-400 to-purple-500 bg-clip-text text-transparent">
              AI 计算平台
            </span>
          </h1>

          {/* Subtitle */}
          <p className="text-lg text-muted-foreground text-center max-w-2xl mx-auto mb-10">
            专为昇腾生态打造的开发者平台，提供高性能推理引擎、丰富的模型库和一站式部署解决方案
          </p>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Button variant="cta" size="lg">
              立即开始
            </Button>
            <Button variant="outline" size="lg">
              观看演示
            </Button>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 bg-secondary/5">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center font-heading mb-12">
            为什么选择昇腾生态平台？
          </h2>

          <div className="grid md:grid-cols-3 gap-6">
            <Card>
              <CardHeader>
                <CardTitle>高性能推理</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  基于昇腾芯片深度优化，推理速度提升3倍，支持批量处理和流式推理
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>丰富模型库</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  预置100+主流AI模型，覆盖CV/NLP/语音等领域，一键部署
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>一站式部署</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  从训练到部署全流程支持，容器化部署，一键上线生产环境
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </main>
  );
}
EOF

# Root Layout
cat > app/layout.tsx << 'EOF'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "昇腾生态平台",
  description: "专为昇腾生态打造的开发者平台",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-CN" className="dark">
      <body className="min-h-screen bg-background font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
EOF

echo_success "示例页面创建完成"

# ==========================================================================
# 创建 next-env.d.ts
# ==========================================================================

cat > next-env.d.ts << 'EOF'
/// <reference types="next" />
/// <reference types="next/image-types/global" />
EOF

# ==========================================================================
# 完成
# ==========================================================================

echo ""
echo "=========================================="
echo_success "项目初始化完成！"
echo "=========================================="
echo ""
echo "📁 项目目录: ./$PROJECT_NAME"
echo ""
echo "快速开始:"
echo "  cd $PROJECT_NAME"
echo "  npm run dev"
echo ""
echo "访问: http://localhost:3000"
echo ""
echo "下一步:"
echo "  1. 复制设计系统文件到项目"
echo "     cp ~/.openclaw/workspace/design-systems/* ./"
echo ""
echo "  2. 添加更多 shadcn/ui 组件"
echo "     npx shadcn-ui@latest add badge avatar input"
echo ""
echo "  3. 自定义配色和主题"
echo "     编辑 tailwind.config.ts"
echo ""
