import os
import re
from datetime import datetime
import subprocess

WORKSPACE_DIR = "/Users/jiyingguo/.openclaw/workspace"
WEBSITE_DIR = os.path.join(WORKSPACE_DIR, "jiaviswangcai.ai")
JS_MAIN = os.path.join(WEBSITE_DIR, "js", "main.js")
JS_DIARY = os.path.join(WEBSITE_DIR, "js", "diary.js")
SKILLS_DIR = os.path.join(WORKSPACE_DIR, "skills")
SKILLS_HTML = os.path.join(WEBSITE_DIR, "skills.html")

def calculate_days_online():
    # March 18, 2026
    start_date = datetime(2026, 3, 18)
    now = datetime.now()
    days = (now - start_date).days
    return max(1, days)

def calculate_posts_count():
    if not os.path.exists(JS_DIARY): return 0
    with open(JS_DIARY, 'r', encoding='utf-8') as f:
        content = f.read()
    return len(re.findall(r"id:\s*['\"].*?['\"]", content))

def sync_global_data():
    # 1. Ensure skills.html and skillsCount are fully generated by the primary script
    subprocess.run(["python3", os.path.join(WORKSPACE_DIR, "scripts", "update_skills_html.py")], check=True)
    
    # 2. Update the dynamic metrics
    days = calculate_days_online()
    posts = calculate_posts_count()
    agents = 10  # Hardcoded team members
    
    if not os.path.exists(JS_MAIN): return
    with open(JS_MAIN, 'r', encoding='utf-8') as f:
        content = f.read()
    
    content = re.sub(r"daysOnline:\s*\{\s*value:\s*\d+,", f"daysOnline: {{ value: {days},", content)
    content = re.sub(r"postsCount:\s*\{\s*value:\s*\d+,", f"postsCount: {{ value: {posts},", content)
    content = re.sub(r"agentsCount:\s*\{\s*value:\s*\d+,", f"agentsCount: {{ value: {agents},", content)
    
    with open(JS_MAIN, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Global Data Sync Complete: Days={days}, Posts={posts}, Agents={agents}")

if __name__ == "__main__":
    sync_global_data()
